### ISSUE TITLE
Glob pattern with pipe character breaks Markdown report table

### ISSUE THREAD

**Issue by nuno-m** [LironEr/bundlemon#102]
**Describe the bug**
Using glob patterns with the OR operator (`|`) breaks the generated Markdown report.
These characters are not currently being escaped and when used on a glob pattern, they are interpreted as part of the Markdown syntax.

**Expected behavior**
Glob pattern should be escaped on Markdown report to prevent characters such as `|` from breaking the table.

**Additional context**

***Example Screenshot***
<img width="523" alt="image" src="https://user-images.githubusercontent.com/3770454/170975328-14636d94-7de9-48b9-b57d-9115b1285cb9.png">

Sidenote: I wanted to run this the project locally, and try to work on a fix for this issue, but I wasn't able to.
When running the `yarn start:service` command I get `open [...]/bundlemon/service/.env: no such file or directory` error.

**Comment by LironEr** [comment]
Should be fixed in [bundlemon-markdown-output v1.0.0](https://github.com/LironEr/bundlemon/releases/tag/bundlemon-markdown-output%401.0.0)

BundleMon service with this version is already deployed

Thank you for reporting this issue (:
