### ISSUE TITLE
Bundlemon fails to produce the `checkRun` in v2

### ISSUE THREAD

**Issue by tleunen** [LironEr/bundlemon#147]
**Describe the bug**

I have a project which uses CircleCI to send the reports to BundleMon. Because of this, I added the github token for the tool. But now, it gives me this error with v2 rc1:

```
[ERROR] github output: Create GitHub "checkRun": failure - You must authenticate via a GitHub App.
```

With v1, everything worked fine using the github app, and without providing the token.

**Environment**
BundleMon version: `2.0.0-rc1`

**Comment by LironEr** [comment]
Should be ok now, you can also use token without any scopes.

See [migration guide from v1 to v2](https://github.com/LironEr/bundlemon/blob/master/docs/migration-v1-to-v2.md) for more details.

**Comment by tleunen** [comment]
Thanks for the quick fix! I'll test it again once a new version is released.

**Comment by LironEr** [comment]
it was a change in the server, you can use the same CLI version

**Comment by tleunen** [comment]
I'm still having the same output when I run it.
```
bundlemon: [ERROR] github output: Create GitHub "checkRun": failure - You must authenticate via a GitHub App.
bundlemon: [ERROR] github output: Unknown error
```

**Comment by LironEr** [comment]
oh so sorry, I deployed the server to test env and not to prod.

Hopefully, it should work now (:

I need to create an automated test in CircleCI to check all that stuff...

**Comment by tleunen** [comment]
Haha, it happens :) No worries.

Works fine now!
