### ISSUE TITLE
Screenshot of history in the service?

### ISSUE THREAD

**Issue by paulirish** [LironEr/bundlemon#188]
The free hosted service looks great.   I've been using https://buildtracker.dev/ but exploring alternatives.

Could you share some screenshots of what it looks like? For example I'd definitely love to spot the commit from X weeks ago that bumped up sizes. 

and maybe put one of these screenshots in a readme?

**Comment by LironEr** [comment]
Hey, there is a link in the readme to example history report of the bundle size of BundleMon website.

https://app.bundlemon.dev/projects/60a928cfc1ab380009f5cc0b/reports?branch=master&resolution=all

**Comment by paulirish** [comment]
Beautiful. I love it. Thanks

**Comment by paulirish** [comment]
> [app.bundlemon.dev/projects/60a928cfc1ab380009f5cc0b/reports?branch=master&resolution=all](https://app.bundlemon.dev/projects/60a928cfc1ab380009f5cc0b/reports?branch=master&resolution=all)

this is now at 
https://app.bundlemon.dev/projects/60a928cfc1ab380009f5cc0b/reports?branch=main&resolution=all

and here's the screenshots:

<img width="1344" alt="image" src="https://github.com/user-attachments/assets/47f02338-9561-4403-b64c-1e8a7d248f5f">

<img width="1339" alt="image" src="https://github.com/user-attachments/assets/2504212b-5543-4cfc-8c66-dd786866e9ec">


@LironEr i still think you should add them to your readme, btw!

(i was pointing a colleague at your service as... it is quite a bit better than the [alternatives](https://github.com/GoogleChrome/lighthouse/issues/10472#issuecomment-1865015002))

**Comment by LironEr** [comment]
Yeah, it does look nice 😅 I added them to the readme.

I see that https://github.com/GoogleChrome/lighthouse/issues/10472 is still open, is there any feature you think is missing from BundleMon so you would use it?

Thanks (:
