### ISSUE TITLE
validation failed due to missing branch property when trying to commit bundlemon record 

### ISSUE THREAD

**Issue by benyael15** [LironEr/bundlemon#26]
**Describe the bug**

Suddenly, we are getting error when bundlemon tries to commit its record (without any change on our end)
getting this:

[DEBUG] github-pr output: **branch: "dependabot/npm_and_yarn/ssri-6.0.2**" target branch: "master" PR number: "1483"                                                 
[INFO] Start analyzing                                                                                                                                           
[INFO] Finished analyzing                                                                                                                                        
[INFO] Start generating report                                                                                                                                   
[INFO] Save commit record for branch "dependabot/npm_and_yarn/ssri-6.0.2"                                                                                        
[ERROR] create commit record: validation failed                                                                                                                  
[                                                                                                                                                                
  {                                                                                                                                                              
    **message: '"query.branch" is required**',                                                                                                                       
    path: [ 'query', 'branch' ],                                                                                                                                 
    type: 'any.required',                                                                                                                                        
    context: { label: 'query.branch', key: 'branch' }                                                                                                            
  }                                                                                                                                                              
]                                                                                                                                                                
[ERROR] **Failed to save commit record**     

**Expected behavior**

seems like bundlemon cant recognise the branch name when trying to push the record to storage,
but as you can see the branch name exist in the first line of the output, but under the query object somehow its not valid.

**Environment**
BundleMon version: `^0.3.0-rc.1`

Please run this command inside your project and paste its contents here (it automatically copies to your clipboard)
`npx envinfo --system --binaries --markdown | npx clipboard-cli`

**Additional context**

**Comment by LironEr** [comment]
Should be fixed in [v0.4.0](https://github.com/LironEr/bundlemon/releases/tag/v0.4.0)
