### ISSUE TITLE
Feature proposal - json file output

### ISSUE THREAD

**Issue by shwarcu** [LironEr/bundlemon#55]
**Is your feature request related to a problem? Please describe.**

I would like to process results gathered by bundlemon, I need an interface that would allow saving bundlemon results as a file or ability to attach custom output/reporter to process and save results. Application I am working with is build on a CI server and can't be build by Github Actions. This forces me to measure bundle sizes on the CI server and then process results further for example by sending them to some dashboard or github issue API.

**Describe the solution you'd like**
Ability to store result as json file. Optionally passing file name as parameter.

**Describe alternatives you've considered**
At the moment I could possibly scrap results from the console output but that's very hacky solution.

**Additional context**
I created a draft of a simple output that could possibly satisfy requirements of how bundlemon works, but I didn't test this solution yet. It's a raw draft for feature proposal.

```ts
import fs from 'fs';
import { Report } from 'bundlemon-utils';
import logger from '../../../common/logger';
import type { Output, OutputCreateParams, OutputInstance } from '../types';

const saveAsJson = (filename: string, payload: Report) => {
  fs.writeFile(`${filename}`, JSON.stringify(payload), (error: any) => {
    if (error) {
      logger.log('There was an error when saving a file');
      throw error;
    }
    logger.log(`${filename} saved.`);
  });
};

const output: Output = {
  name: 'json',
  create: (params: OutputCreateParams): OutputInstance | Promise<OutputInstance | undefined> | undefined => {
    const { filename } = params.options;
    const name = filename ? filename : 'bundlemon-results.json';
    return {
      generate: (report: Report): void => saveAsJson(name, report),
    };
  },
};

export default output;

```

**Comment by LironEr** [comment]
Released in [v1.2.0](https://github.com/LironEr/bundlemon/releases/tag/bundlemon%40v1.2.0)

Thank you for your contribution 👍
