### ISSUE TITLE
History report - table header is displayed over poup for the latest date 

### ISSUE THREAD

**Issue by shwarcu** [LironEr/bundlemon#60]
**Describe the bug**
<img width="1754" alt="Screenshot 2021-10-29 at 10 51 50" src="https://user-images.githubusercontent.com/58426925/139408046-5db1bf46-252c-46fc-bdf8-0e434d846782.png">

 When displaying pop for the last day on the history report, the table header is displayed over it (wrong z-index?) Found on Bundlemon history report.

**Expected behaviour**
Popup should be displayed above the table and its header.

**Environment**
BundleMon version: `v1.1.1` 
https://app.bundlemon.dev/

## System:
 - OS: macOS 11.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 3.95 GB / 32.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
 - npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm

**Additional context**
Looks like the issue is caused by table header cell having `z-index: 2;`

**Comment by LironEr** [comment]
Thank you for reporting & fixing this issue!
