### ISSUE TITLE
Error during commit record creation, when bundlemon runs on master branch / Travis

### ISSUE THREAD

**Issue by trollepierre** [LironEr/bundlemon#87]
Hello 👋 

**Describe the bug**
 We could not run bundlemon on master branch inside our project, because prNumber is false.
That makes  [createCommitRecord](https://github.com/LironEr/bundlemon/blob/bafa5fcbe783e19343311c1464d27ad70f3d2104/packages/bundlemon/src/common/service.ts#L48) fail

Consequence to see in this [PR](https://github.com/cozy/cozy-drive/pull/2507)  : Total files change +3.96MB 0% in each PR.

**Expected behavior**

Same working process that in bundlemon project: inside [Github Action last merge commit](https://github.com/LironEr/bundlemon/runs/5199722979?check_suite_focus=true) , it works.

**Environment**
BundleMon version: `v1.3.0`

The concerned .bundlemonrc : 
https://github.com/cozy/cozy-drive/blob/master/.bundlemonrc

## System:
 - OS: macOS 12.1
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 61.59 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.22.9 - ~/.nvm/versions/node/v12.22.9/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 6.14.15 - ~/.nvm/versions/node/v12.22.9/bin/npm
 - Watchman: 2022.02.28.00 - /usr/local/bin/watchman

**Additional context**

Here is the Travis error: 

```
[ERROR] create commit record: validation failed
{
  "message": "A validation error occurred when validating the body",
  "errors": [
    {
      "keyword": "pattern",
      "dataPath": ".prNumber",
      "schemaPath": "#/properties/prNumber/pattern",
      "params": {
        "pattern": "^[0-9]*$"
      },
      "message": "should match pattern \"^[0-9]*$\""
    }
  ]
}
[ERROR] Failed to create commit record
[ERROR] Unhandled error
Error: Failed to generate report
```

Capture:
![Capture d’écran 2022-03-09 à 15 16 03](https://user-images.githubusercontent.com/8363334/157460415-0389ce05-9714-4f04-b284-dce22e0948ad.png)

**Comment by LironEr** [comment]
Thank you for reporting this issue, should be fixed in [v1.3.1](https://github.com/LironEr/bundlemon/releases/tag/bundlemon%40v1.3.1)

Please let me know if it didn't work
